language: python
python:
  - "3.6"  # Minimum version supported by ethereum python tools
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
install:
  - pip install -r requirements.dev.txt
  - python setup.py develop
  - python setup.py install
script:
  - pytest