# flake8: noqa
class SolidbyteException(Exception): pass
class DeploymentError(SolidbyteException): pass
class DeploymentValidationError(DeploymentError): pass
class CompileError(SolidbyteException): pass
class LinkError(CompileError): pass
class ConfigurationError(SolidbyteException): pass
class AccountError(SolidbyteException): pass
class ValidationError(SolidbyteException): pass
class WrongPassword(ValidationError): pass
class ScriptError(SolidbyteException): pass
class InvalidScriptError(ValidationError): pass
